### Upload Image Test
POST http://localhost:8080/api/images/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="image4.png"
Content-Type: image/png

< ./images/image4.png
--WebAppBoundary--

### View Original Image
GET http://localhost:8080/api/images/view/{{imageId}}

### View Thumbnail Image
GET http://localhost:8080/api/images/view/{{imageId}}?thumbnail=true